export const CURRENT_LOGIN = "CURRENT_LOGIN";
export const CURRENT_REGISTRO = "CURRENT_REGISTRO";
export const CURRENT_TUTOR = "CURRENT_TUTOR";
export const CURRENT_LIDER_GRUPO = "CURRENT_LIDER_GRUPO";
export const CURRENT_HELP = "CURRENT_HELP";
export const CURRENT_COMPLETA_PERFIL = "CURRENT_COMPLETA_PERFIL";
export const CURRENT_CAMBIA_CONTRASENA_PERFIL = "CURRENT_CAMBIA_CONTRASENA_PERFIL";
export const CURRENT_SALIR_PERFIL = "CURRENT_SALIR_PERFIL";
export const CURRENT_AVATAR_TUTOR = "CURRENT_AVATAR_TUTOR";
export const CURRENT_ASIGNACIONES = "CURRENT_ASIGNACIONES";
export const CURRENT_ARTICULOS_TUTOR = "CURRENT_ARTICULOS_TUTOR";
export const CURRENT_CAMBIA_CONTRASENA_TUTOR = "CURRENT_CAMBIA_CONTRASENA_TUTOR";
export const CURRENT_SALIR_TUTOR = "CURRENT_SALIR_TUTOR";
export const CURRENT_AVATAR_LIDER = "CURRENT_AVATAR_LIDER";
export const CURRENT_GRUPOS = "CURRENT_GRUPOS";
export const CURRENT_ARTICULOS_LIDER = "CURRENT_ARTICULOS_LIDER";
export const CURRENT_CAMBIA_CONTRASENA_LIDER = "CURRENT_CAMBIA_CONTRASENA_LIDER";
export const CURRENT_SALIR_LIDER = "CURRENT_SALIR_LIDER";
export const GET_TOP_TUTORES = "GET_TOP_TUTORES";
export const GET_COUNT_TUTORES = "GET_COUNT_TUTORES";
export const CURRENT_HOME = "CURRENT_HOME";
export const GET_USER = "SET_USER";
export const GET_MATERIAS = "GET_MATERIAS";
export const GET_MATERIAS_TUTOR = "GET_MATERIAS_TUTOR";
export const GET_DIRECCION_TUTOR = "GET_DIRECCION_TUTOR";
export const GET_MATERIA_DIRECCION_TUTOR = "GET_MATERIA_DIRECCION_TUTOR";
export const GET_DIRECCIONES_ALTERNAS = "GET_DIRECCIONES_ALTERNAS";

export const INITIAL_LOCATION = {
  address: 'Ciudad de México, México',
  position: {
    lat: 19.432608,
    lng: -99.133209
  }
};

export const INITIAL_MAP_ZOOM_LEVEL = 16;

export const ATLANTIC_OCEAN = {
  latitude: 29.532804,
  longitude: -55.491477
};
